name: MyceliumPlague
main: com.gmail.mikeundead.MyceliumPlague
version: 1.2
author: ASC_Dreanor
commands:
  rollback:
    description: Resets everything that has ever been spread on
    usage: /rollback
    default: op